---
    - name: Create a user if it doesn't exist
      user:
        name: "{{ create_user }}"
        shell: /bin/bash
        password: "{{ create_user_password | password_hash('sha512') }}"
        state: present
      when: not user_exists
      tags:
        - create_user

    - name: Update the user's password
      user:
        name: "{{ create_user }}"
        update_password: always
        password: "{{ create_user_password | password_hash('sha512') }}"
      when: not user_exists
      tags:
        - update_password

    - name: Provide sudo permissions to the user
      lineinfile:
        path: /etc/sudoers
        line: '{{ create_user }} ALL=(ALL:ALL) ALL'
      when: not user_exists
      tags:
        - sudo_permissions

    - name: Copy SSH public key to the user's home directory
      authorized_key:
        user: "{{ create_user }}"
        key: "{{ ssh_public_key }}"
      when: not user_exists
      tags:
        - copy_ssh_key
